# fly.toml app configuration file generated for mr-frontend-challenge on 2023-07-31T12:48:36+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mr-frontend-challenge"
primary_region = "syd"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
